meta_product_name: "MeloDeal"
meta_title: "MeloDeal - Find a musician, easy!"
meta_description: "finding an high quality live act for a small event"
meta_image: "cover.png" # should exist in `app/assets/images/`
